name: Release Extensions
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Liquibase Version'
        required: true

jobs:
  trigger-release:
    name: "Trigger Releases"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        extension:
          - liquibase-postgresql
          - liquibase-oracle
          - liquibase-cassandra
          - liquibase-hanadb
          - liquibase-hibernate
    steps:
      - name: Release liquibase/${{ matrix.extension }} v${{ github.event.inputs.version }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            console.log("Sending liquibase-release event to liquibase/${{ matrix.extension }}");

            await github.repos.createDispatchEvent({
               "owner": "liquibase",
               "repo": ${{ matrix.java }},
               "event_type": "liquibase-release",
               "client_payload": {
                  "liquibaseVersion": "${{ github.event.inputs.version }}"
                }
             });
